In [1]:
import cv2
import numpy as np
import math
 
def rgbtohsi(rgb_lwpImg):
    rows = int(rgb_lwpImg.shape[0])
    cols = int(rgb_lwpImg.shape[1])
    b, g, r = cv2.split(rgb_lwpImg)
    # 归一化到[0,1]
    b = b / 255.0
    g = g / 255.0
    r = r / 255.0
    hsi_lwpImg = rgb_lwpImg.copy()
    H, S, I = cv2.split(hsi_lwpImg)
    for i in range(rows):
        for j in range(cols):
            num = 0.5 * ((r[i, j]-g[i, j])+(r[i, j]-b[i, j]))
            den = np.sqrt((r[i, j]-g[i, j])**2+(r[i, j]-b[i, j])*(g[i, j]-b[i, j]))
            theta = float(np.arccos(num/den))
 
        if den == 0:
            H = 0
        elif b[i, j] <= g[i, j]:
            H = theta
        else:
            H = 2*math.pi - theta
 
        min_RGB = min(min(b[i, j], g[i, j]), r[i, j])
        sum = b[i, j]+g[i, j]+r[i, j]
        if sum == 0:
            S = 0
        else:
            S = 1 - 3*min_RGB/sum
 
        H = H/(2*3.14159265)
        I = sum/3.0
       # 输出HSI图像，扩充到255以方便显示，一般H分量在[0,2pi]之间，S和I在[0,1]之间
        hsi_lwpImg[:,:,0] = H*255
        hsi_lwpImg[:,:,1] = S*255
        hsi_lwpImg[:,:,2] = I*255
    return hsi_lwpImg

In [ ]:
# HSI转RGB
def HsiToRgb(HSI_image):
    rows,cols = hsi_image.shape
    H,S,I = cv2.split(hsi_image)
    H /= 255.0
    S /= 255.0
    I /= 255.0
    RGB_img = HSI_img.copy()
    R,G,B = cv2.split(RGB_img)
    for i in range(rows):
        for j in range(cols):
            if H[i,j] >= 0 and H[i,j] < 2*math.pi/3.0:
                H[i,j] = H[i,j]
            elif H[i,j]>=2*math.pi/3.0 and H[i,j] < 2*math.pi*2/3.0:
                H[i,j] = H[i,j] - 2*math.pi/3.0
            else:
                H[i,j] = H[i,j] - 2*math.pi*2/3.0
            B[i,j] = I[i,j]*(1-S[i,j])
            temp = S[i,j]*np.cos(H[i,j])/np.cos(math.pi/3.0-H[i,j])
            R[i,j] = I[i,j]*(1+temp)
            G[i,j] = 3*I[i,j]-(R[i,j]+B[i,j]) 
    RGB_img[:,:,0] = B*255
    RGB_img[:,:,1] = R*255
    RGB_img[:,:,2] = R*255
    return RGB_img

In [2]:
import cv2
import numpy as np
if __name__ == '__main__':
    path = 'E:/Download/image/our485/high/10.PNG'
    image = cv2.imread(path)
    print(image.shape)
    
    cv2.namedWindow("window");

    cv2.imshow('window',image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

(400, 600, 3)


In [3]:
hsi_img2 = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
rgb_img3 = cv2.cvtColor(hsi_img2,cv2.COLOR_HSV2BGR)
print(hsi_img2[:,:,2])
cv2.namedWindow("window");
cv2.imshow('window',hsi_img2[:,:,2])
cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 86  87  86 ... 138 138 138]
 [ 86  86  86 ... 139 139 139]
 [ 84  86  84 ... 139 139 138]
 ...
 [ 77  73  75 ... 178 178 179]
 [ 73  73  79 ... 177 181 179]
 [ 75  75  73 ... 177 176 178]]


In [36]:
H,S,I = cv2.split(hsi_img2)
#print(I)
I_1 = I
I = I//6
#print(I)
#print(H.shape,S.shape,I.shape)
HSI_IMAGE = cv2.merge([H,S,I])
RGB_IMAGE = cv2.cvtColor(HSI_IMAGE,cv2.COLOR_HSV2BGR)
cv2.namedWindow("wi");
cv2.imshow('wi',HSI_IMAGE)
cv2.namedWindow('w2')
cv2.imshow('w2',RGB_IMAGE)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [39]:
print(I_1)
a = np.random.uniform(0,0.5,I_1.shape)
print(a)
I = a*I_1
print(I)
I = np.array(I,dtype='uint8')
print(I)

[[ 86  87  86 ... 138 138 138]
 [ 86  86  86 ... 139 139 139]
 [ 84  86  84 ... 139 139 138]
 ...
 [ 77  73  75 ... 178 178 179]
 [ 73  73  79 ... 177 181 179]
 [ 75  75  73 ... 177 176 178]]
[[0.21458782 0.21470408 0.31770007 ... 0.37599469 0.44690441 0.25165167]
 [0.26626582 0.44919214 0.30058686 ... 0.20994857 0.49736781 0.42804341]
 [0.42513789 0.20238658 0.38817373 ... 0.36615733 0.49082457 0.11160303]
 ...
 [0.29056051 0.33723012 0.30458074 ... 0.08275714 0.2037228  0.22999403]
 [0.42017027 0.21262431 0.04217305 ... 0.47753103 0.11874543 0.35278264]
 [0.41324638 0.23261216 0.16540824 ... 0.36938881 0.00577137 0.02619941]]
[[18.45455254 18.6792549  27.322206   ... 51.88726728 61.67280815
  34.72793006]
 [22.8988605  38.63052364 25.85046974 ... 29.18285058 69.13412598
  59.49803346]
 [35.7115828  17.4052457  32.60659293 ... 50.89586934 68.22461494
  15.40121845]
 ...
 [22.37315954 24.6177987  22.84355535 ... 14.73077051 36.26265887
  41.16893099]
 [30.67243001 15.52157464  3.331670

In [40]:
print(H.dtype,S.dtype,I.dtype)
HSI_IMAGE = cv2.merge([H,S,I])
RGB_IMAGE = cv2.cvtColor(HSI_IMAGE,cv2.COLOR_HSV2BGR)
cv2.namedWindow("w1");
cv2.imshow('w1',HSI_IMAGE)
cv2.namedWindow('w3')
cv2.imshow('w3',RGB_IMAGE)

cv2.waitKey(0)
cv2.destroyAllWindows()

uint8 uint8 uint8


In [49]:
path = 'E:/Download/image/59.jpg'
image_1 = cv2.imread(path)
#image_1 = cv2.resize(image_1,(500,500))
cv2.namedWindow('w4')
cv2.imshow('w4',image_1)
image_1 = cv2.resize(image_1,(400,400))
cv2.namedWindow('w5')
cv2.imshow('w5',image_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
import os
import numpy as np
import matplotlib.image as mp
#from skimage import img_as_ubyte
from PIL import Image


path = 'E:\Download\high\our485\high\\'     
savepath = 'E:\Download\high\\'   
filelist = os.listdir(path)  # 打开对应的文件夹
num = len(filelist)  #得到文件夹中图像的个数
#print(filelist)
print(num)

for index,imagename in enumerate(filelist):
    NewName = imagename
    NewName = NewName.split('.')
    if index < 10:        
        NewName[0] = str(index)
    elif  index>=10 and index <100:
        NewName[0] = str(index)
    else:
        NewName[0] = str(index)
    if NewName[-1] != 'jpg':
        NewName[-1] = 'jpg'
        NewName = str.join('.',NewName)
        imagename = path + imagename
        NewName = path + NewName
        os.rename(imagename,NewName)
        print(NewName,'修改成功！')
    else:
        NewName[-1] = 'jpg'
        NewName = str.join('.',NewName)
        imagename = path + imagename
        NewName = path + NewName
        os.rename(imagename,NewName)
        print(NewName,'修改成功！') 

500
E:\Download\high\our485\high\0.jpg 修改成功！
E:\Download\high\our485\high\1.jpg 修改成功！
E:\Download\high\our485\high\2.jpg 修改成功！
E:\Download\high\our485\high\3.jpg 修改成功！
E:\Download\high\our485\high\4.jpg 修改成功！
E:\Download\high\our485\high\5.jpg 修改成功！
E:\Download\high\our485\high\6.jpg 修改成功！
E:\Download\high\our485\high\7.jpg 修改成功！
E:\Download\high\our485\high\8.jpg 修改成功！
E:\Download\high\our485\high\9.jpg 修改成功！
E:\Download\high\our485\high\10.jpg 修改成功！
E:\Download\high\our485\high\11.jpg 修改成功！
E:\Download\high\our485\high\12.jpg 修改成功！
E:\Download\high\our485\high\13.jpg 修改成功！
E:\Download\high\our485\high\14.jpg 修改成功！
E:\Download\high\our485\high\15.jpg 修改成功！
E:\Download\high\our485\high\16.jpg 修改成功！
E:\Download\high\our485\high\17.jpg 修改成功！
E:\Download\high\our485\high\18.jpg 修改成功！
E:\Download\high\our485\high\19.jpg 修改成功！
E:\Download\high\our485\high\20.jpg 修改成功！
E:\Download\high\our485\high\21.jpg 修改成功！
E:\Download\high\our485\high\22.jpg 修改成功！
E:\Download\high\our485\high\23.jpg 修改成功

In [9]:
#低照度图像合成
import cv2
path = 'E:\Download\high\our485\high\\'
filelist = os.listdir(path)
savepath = 'E:\Download\high\our485\low\\'
low_rate = np.random.uniform(0.1,0.5,len(filelist))
#print(low_rate)
print(filelist)
for index,imagename in enumerate(filelist):
    #print(index,imagename)
    imagepath = path + imagename
    print(imagepath)
    image = cv2.imread(imagepath)
    image_Hsi = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
    H,S,I = cv2.split(image_Hsi)
    I = I*low_rate[index]
    I = np.array(I,dtype = 'uint8' )
    img  = cv2.merge([H,S,I])
    image_RGB = cv2.cvtColor(img,cv2.COLOR_HSV2BGR)
    cv2.imwrite(savepath+imagename,image_RGB)
    print(savepath+imagename,"写入成功")

['0.jpg', '1.jpg', '10.jpg', '100.jpg', '101.jpg', '102.jpg', '103.jpg', '104.jpg', '105.jpg', '106.jpg', '107.jpg', '108.jpg', '109.jpg', '11.jpg', '110.jpg', '111.jpg', '112.jpg', '113.jpg', '114.jpg', '115.jpg', '116.jpg', '117.jpg', '118.jpg', '119.jpg', '12.jpg', '120.jpg', '121.jpg', '122.jpg', '123.jpg', '124.jpg', '125.jpg', '126.jpg', '127.jpg', '128.jpg', '129.jpg', '13.jpg', '130.jpg', '131.jpg', '132.jpg', '133.jpg', '134.jpg', '135.jpg', '136.jpg', '137.jpg', '138.jpg', '139.jpg', '14.jpg', '140.jpg', '141.jpg', '142.jpg', '143.jpg', '144.jpg', '145.jpg', '146.jpg', '147.jpg', '148.jpg', '149.jpg', '15.jpg', '150.jpg', '151.jpg', '152.jpg', '153.jpg', '154.jpg', '155.jpg', '156.jpg', '157.jpg', '158.jpg', '159.jpg', '16.jpg', '160.jpg', '161.jpg', '162.jpg', '163.jpg', '164.jpg', '165.jpg', '166.jpg', '167.jpg', '168.jpg', '169.jpg', '17.jpg', '170.jpg', '171.jpg', '172.jpg', '173.jpg', '174.jpg', '175.jpg', '176.jpg', '177.jpg', '178.jpg', '179.jpg', '18.jpg', '180.jpg', 

In [89]:
for i in range(total_num):
    jpg_name = path + str(i + 1) + '.jpg' #拼接图像的读取地址
    #对图像数据类型进行转换
    image = mp.imread(jpg_name)
    image = img_as_ubyte(image)
    result_img = Image.fromarray(image)
    #保存图像
    savejpg_name = savepath + str(i + 1) + '.jpg'  #拼接保存图像的地址
    result_img.save(savejpg_name) #保存图像

NameError: name 'img_as_ubyte' is not defined

In [104]:
'''
for imagename in filelist:
    Img_path = path + imagename
    image = cv2.imread(Img_path)
    if image is None:
        continue
    result_image = cv2.resize(image,(300,300))
    result_image = Image.fromarray(result_image)
    savepath = Img_path
    result_image.save(savepath)
    print(savepath,'修改保存成功')
'''

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [123]:
a = np.random.uniform(1,100,4)
print(a)
print(a.dtype)
a = np.array(a,dtype='uint8')
print(a)

[90.3130802  85.863057   52.54937357 24.75794066]
float64
[90 85 52 24]


In [4]:
print(len(os.listdir('E:\Download\image\our485\high')))

479
