In [1]:
import cv2
import numpy as np


def replaceZeroes(data):
    min_nonzero = min(data[np.nonzero(data)])
    data[data == 0] = min_nonzero
    return data


def MSR(img, scales):
    weight = 1 / 3.0
    scales_size = len(scales)
    h, w = img.shape[:2]
    log_R = np.zeros((h, w), dtype=np.float32)

    for i in range(scales_size):
        img = replaceZeroes(img)
        L_blur = cv2.GaussianBlur(img, (scales[i], scales[i]), 0)
        L_blur = replaceZeroes(L_blur)
        dst_Img = cv2.log(img/255)
        dst_Lblur = cv2.log(L_blur/255)
        dst_Ixl = cv2.multiply(dst_Img, dst_Lblur)
        log_R += weight * cv2.subtract(dst_Img, dst_Ixl)
        log_R = 
        cv2.imshow('lor',log_R)
        data = np.random.rand(*log_R.shape)
        ig =  log_R*data
        cv2.imshow('ig',ig)

    dst_R = cv2.normalize(log_R,None, 0, 255, cv2.NORM_MINMAX)
    log_uint8 = cv2.convertScaleAbs(dst_R)
    return log_uint8


if __name__ == '__main__':
    img = 'E:/Download/image/our485/high/5.png'
    scales = [15,101,301]  # [3,5,9]  #看不出效果有什么差别
    #cv2.imshow(img)
    src_img = cv2.imread(img)
    cv2.imshow('imae',src_img)
    b_gray,g_gray, r_gray = cv2.split(src_img)
    b_gray = MSR(b_gray, scales)
    g_gray = MSR(g_gray, scales)
    r_gray = MSR(r_gray, scales)
    result = cv2.merge([b_gray, g_gray, r_gray])

    cv2.imshow('img',src_img)
    cv2.imshow('MSR_result',result)
    cv2.waitKey(0)

    cv2.destroyAllWindows()

error: OpenCV(4.2.0) ..\modules\core\src\mathfuncs.cpp:702: error: (-215:Assertion failed) depth == CV_32F || depth == CV_64F in function 'cv::log'


In [6]:
import numpy as np
def replaceZeroes(data):
    min_nonzero = min(data[np.nonzero(data)])
    print(min_nonzero)
    data[data == 0] = min_nonzero
    print(data)
    return data
data = np.random.randn(3,3)
print(data)
data = replaceZeroes(data)
print(data)

[[-0.05717079 -1.27542703  1.40384814]
 [-2.45594299  0.18762228 -0.52658279]
 [ 0.24490671 -0.53954896 -0.71408392]]
-2.455942989000967
[[-0.05717079 -1.27542703  1.40384814]
 [-2.45594299  0.18762228 -0.52658279]
 [ 0.24490671 -0.53954896 -0.71408392]]
[[-0.05717079 -1.27542703  1.40384814]
 [-2.45594299  0.18762228 -0.52658279]
 [ 0.24490671 -0.53954896 -0.71408392]]


In [11]:
datas = np.random.rand(*data.shape)
print(datas)

[[0.16262678 0.12017644 0.49191095]
 [0.75646443 0.69754855 0.50906499]
 [0.45079457 0.62908116 0.82454888]]


In [9]:
print(data.shape)

(3, 3)
