# 神经网络算法复杂度分析

In [1]:
import torch
import numpy as np
torch.cuda.is_available()

True

$CPU 2.3G = 2.3 * 10^9$ 

$10000*10000*(10000+10000)  = 2*10^{12}$

$\dfrac{10^{12}}{10^9}$

In [2]:
print((1/2.3)*1000)

434.78260869565224


In [3]:
# 矩阵乘法
a = torch.tensor([[1,0,0],[0,1,0],[0,1,1]])
b = torch.tensor([[1,1,1],[1,1,1],[1,1,1]])
print(a@b)

tensor([[1, 1, 1],
        [1, 1, 1],
        [2, 2, 2]])


In [11]:
%%time
a = torch.randn(10000,10000)
b = torch.randn(10000,10000)

Wall time: 9.29 s


In [13]:
%%time
print(a@b)

tensor([[  96.0543,  -65.1760, -128.2325,  ...,  132.9977,  -31.5391,
           61.3325],
        [ -86.2178,  145.5776,  -17.3860,  ...,  110.1099,  -28.3264,
          -58.4837],
        [  65.1780,  -75.5555,  -70.5671,  ...,  -30.0032,  -35.4234,
          -34.3246],
        ...,
        [ -56.6164, -188.7684,  132.5836,  ...,  135.5719,  220.9708,
           41.1055],
        [-206.7721,   -6.7397,   -9.4560,  ...,  -29.0191,  116.2361,
           -6.3715],
        [ -20.6171,   70.6530,  -35.7347,  ...,   87.1081,  -31.6311,
         -111.8333]])
Wall time: 34.9 s


In [16]:
%%time
device = torch.device('cuda:0')
a = a.to(device)
b = b.to(device)

RuntimeError: CUDA error: unspecified launch failure

In [6]:
%%time
print(a@b)

RuntimeError: cuda runtime error (4) : unspecified launch failure at C:/w/1/s/tmp_conda_3.7_055306/conda/conda-bld/pytorch_1556690124416/work/aten/src\THC/THCReduceAll.cuh:327

In [7]:
print(25*1000/98)

255.10204081632654


In [8]:
%%time
o = torch.randn(10000,10000)
p = torch.randn(10000,10000)
print(o.mul(p))

tensor([[-1.3726, -0.3364,  0.3434,  ...,  0.1459,  1.5688, -0.3890],
        [ 2.5022,  0.0301, -0.0081,  ..., -0.1627,  0.6258, -1.7774],
        [ 0.0724,  0.0144,  0.1213,  ..., -0.1109, -0.0969, -4.0226],
        ...,
        [-0.1794,  1.1548,  0.2996,  ...,  1.0468, -0.5760,  0.0388],
        [ 0.3461,  0.3167,  0.1865,  ..., -0.0944,  0.0368, -0.4600],
        [-0.5220,  0.0435, -0.6017,  ..., -0.1803,  0.1002,  0.9812]])
Wall time: 10 s


可以看到我2.6GGPU每秒指令执行次数为$2.6*10^9$

而10000x10000的矩阵的哈达玛积的运算次数为$10^8$

故计算出的时间为 $\dfrac{1}{10}$ s

但是由于CPU的每次乘法或加法的指令数的原因假设指令数为10

则最终的计算是以秒为单位

In [9]:
%%time
o = o.cuda()
p = p.cuda()

RuntimeError: CUDA error: unspecified launch failure

In [10]:
%%time
print(o.mul(p))

tensor([[-1.3726, -0.3364,  0.3434,  ...,  0.1459,  1.5688, -0.3890],
        [ 2.5022,  0.0301, -0.0081,  ..., -0.1627,  0.6258, -1.7774],
        [ 0.0724,  0.0144,  0.1213,  ..., -0.1109, -0.0969, -4.0226],
        ...,
        [-0.1794,  1.1548,  0.2996,  ...,  1.0468, -0.5760,  0.0388],
        [ 0.3461,  0.3167,  0.1865,  ..., -0.0944,  0.0368, -0.4600],
        [-0.5220,  0.0435, -0.6017,  ..., -0.1803,  0.1002,  0.9812]])
Wall time: 678 ms


GPU运算速度大概是CPU运算速度的60倍左右