### 设置tensor和tensor元素类型

In [1]:
import torch
#查看tensor默认数据类型
print(torch.tensor([1,1]).dtype)
print(torch.tensor([1.1,2]).dtype)

torch.int64
torch.float32


In [2]:
# 设置指定类型
torch.set_default_dtype(torch.float64)
torch.tensor([1.1,2]).dtype

torch.float64

In [3]:
#还可以通过下面形式设置
torch.set_default_tensor_type(torch.FloatTensor)
torch.get_default_dtype()

torch.float32

### torch.numel计算张量元素总数

In [4]:
a = torch.randn(1,2,3,4,5)
torch.numel(a)

120

### Creation tensor ops
> 随机样本创建操作是一个表,随机样本的创建有下面几种操作
torch.rand() 
torch.rand_like() 
torch.randn()
torch.randn_like() torch.randint() torch.randint_like() torch.randperm()
也可以使用torch.empty()使得样本值服从一个更广范围的分布

`torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False) → Tensor`
```python
|-参数解释:
    data:数据可以是列表元组或者是Numpy数组,标量或者是其他类型
    dtype:数据类型如果None则数据类型来自于data
    device:设备设置CPU FOR CPU,CUDA FOR CUDA
    requires_grad:自动梯度计算设置返回一个梯度张量,默认为False
    pin_memory:锁业内存设置默认False具体理解看下面链接：
        http://www.voidcn.com/article/p-fsdktdik-bry.html
Warning:torch.tensor()总是在拷贝数据,如果想避免拷贝可以使用torch.Tensor.requires_grad_() or torch.Tensor.detach(),if 有一个Numpy数组需要避免拷贝可以使用torch.as_tensor()
```


In [5]:
import numpy as np
a = torch.tensor([[0.1,1.2],[1,2],[3,4]])
print(a)
c = np.random.randint(10,size=(3,4)) # Numpy随机数组
print(c)
#将Numpy随机数组转化成tensor
print(torch.tensor(c))

tensor([[0.1000, 1.2000],
        [1.0000, 2.0000],
        [3.0000, 4.0000]])
[[6 3 3 5]
 [9 8 9 5]
 [5 4 1 8]]
tensor([[6, 3, 3, 5],
        [9, 8, 9, 5],
        [5, 4, 1, 8]], dtype=torch.int32)


`torch.eye(n,m=None,out=None)`
返回一个对角线元素为一的2维张量
* n:行数
* m:列数
* out:输出张量类型

In [6]:
print(torch.eye(3))
print(torch.eye(3,4))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


`torch.from_numpy(ndarray)->tensor`
将Numpy数组装换成张量形式且返回的张量tensor和numpy共享同一
内存空间修改一个会改变另一个

In [7]:
a = np.array([1,2,3,4])
t = torch.from_numpy(a)
print(a)
print(t)
t[0] = 0
print(t)
print(a)

[1 2 3 4]
tensor([1, 2, 3, 4], dtype=torch.int32)
tensor([0, 2, 3, 4], dtype=torch.int32)
[0 2 3 4]


`torch.linspace(start,end,steps=100,out=None)->tensor`
返回star和end间元素以等差数列排列个数为steps的一维张量其实就是均匀采样

In [8]:
torch.linspace(1,10,steps=5)

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [9]:
torch.linspace(-10,10,steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

`torch.logspace(start,end,steps=100,out=None)->tensor`
和上面的线性采样类似,这个是在以10为底的对数函数上的均匀采样范围为$10^{star}到10^{end}$,采样个数为steps

In [10]:
torch.logspace(start=-10,end=10,steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

`torch.ones(*sizes,out=None)->Tensor`
返回一个全为1的张量,shape由可变参数sizes定义

In [11]:
#下面三式等价sizes可以为序列
print(torch.ones(3,3))
print(torch.ones([3,3]))
print(torch.ones((3,3)))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


`torch.rand(*size,out=None)->tensor`
返回一个在[0,1]范围均匀分布的随机数

In [12]:
print(torch.rand((3,3)))
print(torch.rand(3))

tensor([[0.0261, 0.3571, 0.6326],
        [0.1159, 0.8533, 0.4729],
        [0.6475, 0.8471, 0.5449]])
tensor([0.3332, 0.1701, 0.9111])


`torch.randn(*sizes,out=None)->Tensor`

返回一个从标准正态分布中抽取出的随机张量

In [13]:
torch.randn([3,3])

tensor([[-0.4944,  0.2861, -1.0668],
        [ 0.8469, -0.8389,  0.0439],
        [-0.4375, -1.0182, -0.3186]])

`torch.randperm(n,out=None)->LongTensor`

输入参数`n`返回一个从`0`至`n-1`的一个随机整数排列

In [14]:
torch.randperm(5)

tensor([0, 3, 4, 2, 1])

`torch.arange(start,end,step=1,out=None)->tensor`

返回一个1维张量，长度为floor((end−start)/step),floor代表向下取整。包含从start到end，以step为步长的一组序列值(默认步长为1)。

In [15]:
print(torch.arange(*[1,9]))
print(torch.arange(*[1,9],step=2))

tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([1, 3, 5, 7])


`torch.range(start,end,step=1,out=None)->Tensor`

返回一个1维张量，长度为floor((end−start)/step)+1，其中floor代表向下取整数。从start开始，end为结尾，以step为步长的一组值。 step 是两个值之间的间隔，即 Xi+1=Xi+step

In [16]:
print(torch.range(1.0,9))
print(torch.range(1.0,9,step=2))

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  """Entry point for launching an IPython kernel.


tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: UserWarning: torch.range is deprecated in favor of torch.arange and will be removed in 0.5. Note that arange generates values in [start; end), not [start; end].
  


tensor([1., 3., 5., 7., 9.])


`torch.zeros(*sizes,out=None)->Tensor`

返回一个全零张量

In [17]:
torch.zeros(*[3,3])

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

`torch.cat(tensor,dim=0,out=None)->Tensor`
* tensor:张量
* dim:连接维度
* out:输出

In [20]:
torch.cuda.set_device(0)
a = torch. rand( 1000, 1000) 
b = torch. rand( 1000, 1000)
print(a. matmul( b))
print(torch.cuda.is_available())
#将 张量 转移 到 GPU
a = a.cuda() 
b = b.cuda()
print(a.matmul(b))

AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

In [ ]:
print(1)